[character]
success_symbol = "[ ](bold green)"
error_symbol = "[ ](bold red)"

[aws]
symbol = " "
format = '[($symbol$profile )]($style)'

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[gcloud]
symbol = " "
format = '[($symbol$project )]($style)'
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "
disabled = true

[php]
symbol = " "

[python]
symbol = " "
format = "[${symbol}${pyenv_prefix}${version}( \\($virtualenv\\))]($style) "
style = "italic yellow"

[ruby]
symbol = " "

[rust]
symbol = " "
